name: Pipeline

on:
  push:
    branches: master

jobs:
  bump-and-publish:
    name: Bump version and Publish to Github Container Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure git name and email
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'action@github.com'

      - name: Setup node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Bump version
        id: version-bump
        run: echo "::set-output name=RELEASE_VERSION::$(npm version patch -m 'Bump version to v%s')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/oslokommune/ok-origo-dataplatform/dataplatform-frontend:latest
            ghcr.io/oslokommune/ok-origo-dataplatform/dataplatform-frontend:${{ steps.version-bump.outputs.RELEASE_VERSION }}

      - name: Push version bump
        run: git push
