name: Pipeline

on:
  push:
    branches: master

jobs:
  bump:
    name: Bump version
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Fetch code
        with:
          ref: ${{ github.ref }}
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to Github Container Registry
    needs: bump
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-env name=RELEASE_VERSION::$(jq -r .version package.json)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/oslokommune/ok-origo-dataplatform/dataplatform-frontend:latest
            ghcr.io/oslokommune/ok-origo-dataplatform/dataplatform-frontend:${{ env.RELEASE_VERSION }}
